#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].system_chn > "/dev/null"; then
	uci -q batch <<-EOF
		set system.@system[0].timezone="GMT7"
		set system.@system[0].zonename="Asia/Bangkok"

		delete system.ntp.server
		add_list system.ntp.server="time1.apple.com"
		add_list system.ntp.server="time1.google.com"
		add_list system.ntp.server="time.cloudflare.com"
		add_list system.ntp.server="pool.ntp.org"

		set system.@imm_init[0].system_chn="1"
		commit system
	EOF
fi

opkg_mirror="$(uci -q get system.@imm_init[0].opkg_mirror)"
if [ -z "$opkg_mirror" ]; then
	opkg_mirror="https://downloads.openwrt.org"
	uci -q batch <<-EOF
		set system.@imm_init[0].opkg_mirror="$opkg_mirror"
		commit system
	EOF
fi

sed -i.bak "s,https://downloads.immortalwrt.org,$opkg_mirror,g" "/etc/opkg/distfeeds.conf"

exit 0
